# File generated by aws2tf see https://github.com/aws-samples/aws2tf
resource "aws_codepipeline" "pipe-deploy-apps-eks" {
  name       = "deploy-apps-eks"
  depends_on = [aws_iam_role.AWSCodePipelineServiceRole-pipe-eksworkshop-app]
  role_arn   = aws_iam_role.AWSCodePipelineServiceRole-pipe-eksworkshop-app.arn
  tags       = {}

  artifact_store {
    location = aws_s3_bucket.codepipeline-bucket.bucket
    type     = "S3"
  }

  stage {
    name = "Source"

    action {
      category = "Source"
      configuration = {
        "BranchName"           = "master"
        "OutputArtifactFormat" = "CODE_ZIP"
        "PollForSourceChanges" = "true"
        "RepositoryName"       = "eksworkshop-app"
      }
      input_artifacts = []
      name            = "Source"
      namespace       = "SourceVariables"
      output_artifacts = [
        "SourceArtifact",
      ]
      owner     = "AWS"
      provider  = "CodeCommit"
      region    = data.aws_region.current.name
      run_order = 1
      version   = "1"
    }
  }
  stage {
  name = "Approve"

  action {
    name     = "Approval"
    category = "Approval"
    owner    = "AWS"
    provider = "Manual"
    version  = "1"

    # configuration {
    #   NotificationArn = "${var.approve_sns_arn}"
    #   CustomData = "${var.approve_comment}"
    #   ExternalEntityLink = "${var.approve_url}"
    # }
    }
  }
  
  stage {
    name = "Build"

    action {
      category = "Build"
      configuration = {
        "ProjectName" = "eks-cicd-build-app"
      }
      input_artifacts = [
        "SourceArtifact",
      ]
      name      = "Build"
      namespace = "BuildVariables"
      output_artifacts = [
        "BuildArtifact",
      ]
      owner     = "AWS"
      provider  = "CodeBuild"
      region    = data.aws_region.current.name
      run_order = 1
      version   = "1"
    }
  }
}


# File generated by aws2tf see https://github.com/aws-samples/aws2tf
resource "aws_codepipeline" "pipe-eksworkshop-app-delete" {
  name       = "delete-apps-eks"
  depends_on = [aws_iam_role.AWSCodePipelineServiceRole-pipe-eksworkshop-app]
  role_arn   = aws_iam_role.AWSCodePipelineServiceRole-pipe-eksworkshop-app.arn
  tags       = {}

  artifact_store {
    location = aws_s3_bucket.codepipeline-bucket.bucket
    type     = "S3"

  }

  stage {
    name = "Source"

    action {
      category = "Source"
      configuration = {
        "BranchName"           = "master"
        "OutputArtifactFormat" = "CODE_ZIP"
        "PollForSourceChanges" = "true"
        "RepositoryName"       = "eksworkshop-app"
      }
      input_artifacts = []
      name            = "Source"
      namespace       = "SourceVariables"
      output_artifacts = [
        "SourceArtifact",
      ]
      owner     = "AWS"
      provider  = "CodeCommit"
      region    = data.aws_region.current.name
      run_order = 1
      version   = "1"
    }
  }
  stage {
  name = "Approve"

  action {
    name     = "Approval"
    category = "Approval"
    owner    = "AWS"
    provider = "Manual"
    version  = "1"

    # configuration {
    #   NotificationArn = "${var.approve_sns_arn}"
    #   CustomData = "${var.approve_comment}"
    #   ExternalEntityLink = "${var.approve_url}"
    # }
    }
  }
  
  stage {
    name = "Delete-Apps"

    action {
      category = "Build"
      configuration = {
        "ProjectName" = "eks-cicd-delete-apps"
      }
      input_artifacts = [
        "SourceArtifact",
      ]
      name      = "Build"
      namespace = "BuildVariables"
      output_artifacts = [
        "BuildArtifact",
      ]
      owner     = "AWS"
      provider  = "CodeBuild"
      region    = data.aws_region.current.name
      run_order = 1
      version   = "1"
    }
  }
}
