---
apiVersion: v1
kind: Namespace
metadata:
  name: flask-web-app
---
---
apiVersion: v1
kind: Secret
metadata:
  name: flaskapi-secrets
  namespace: flask-web-app
type: Opaque
data:
  mongodb_password: redacted